import React, { useState, useEffect } from 'react';
import { Bot, Activity, AlertCircle, CheckCircle } from 'lucide-react';
import api from '../../services/api';

const AISummaryBox = ({ patientId, theme = 'light' }) => {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const t = theme === 'dark' ? {
    bg: 'rgba(15,23,42,0.6)', border: '1px solid rgba(139,92,246,0.2)',
    textPri: '#F1F5F9', textSec: '#94A3B8', textMuted: '#64748B',
    cardBg: 'rgba(255,255,255,0.03)', cardBorder: '1px solid rgba(255,255,255,0.06)'
  } : {
    bg: 'rgba(255,255,255,0.7)', border: '1px solid rgba(139,92,246,0.3)',
    textPri: '#1E293B', textSec: '#64748B', textMuted: '#94A3B8',
    cardBg: 'rgba(255,255,255,0.5)', cardBorder: '1px solid rgba(139,92,246,0.15)'
  };

  useEffect(() => {
    if (!patientId) return;
    
    setLoading(true);
    api.get(`/api/ai/summary/${patientId}`)
      .then(res => {
        setSummary(res.data);
        setError(null);
      })
      .catch(err => {
        console.error("Failed to load AI summary:", err);
        setError("AI summary unavailable");
      })
      .finally(() => {
        setLoading(false);
      });
  }, [patientId]);

  if (loading) {
    return (
      <div style={{
        padding: '16px', borderRadius: '18px', background: t.bg, border: t.border,
        backdropFilter: 'blur(16px)', WebkitBackdropFilter: 'blur(16px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '120px'
      }}>
        <div style={{ width: '16px', height: '16px', border: '2px solid #8B5CF6', borderTopColor: 'transparent', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
      </div>
    );
  }

  if (error || !summary) {
    return (
      <div style={{
        padding: '16px', borderRadius: '18px', background: t.bg, border: t.border,
        backdropFilter: 'blur(16px)', WebkitBackdropFilter: 'blur(16px)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <AlertCircle style={{ width: '16px', height: '16px', color: t.textMuted }} />
          <span style={{ fontSize: '12px', color: t.textSec }}>{error || "Summary unavailable"}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in" style={{
      padding: '16px 20px', borderRadius: '18px', position: 'relative', overflow: 'hidden',
      background: t.bg, border: t.border,
      backdropFilter: 'blur(16px)', WebkitBackdropFilter: 'blur(16px)',
      boxShadow: theme === 'light' ? '0 4px 24px rgba(139,92,246,0.06)' : 'none',
    }}>
      {/* Top accent bar */}
      <div style={{
        position: 'absolute', top: 0, left: 0, right: 0, height: '3px',
        background: 'linear-gradient(90deg, #8B5CF6 0%, #D946EF 100%)',
      }} />

      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
        <div style={{
          width: '32px', height: '32px', borderRadius: '10px', flexShrink: 0,
          background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.2)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <Bot style={{ width: '16px', height: '16px', color: '#8B5CF6' }} />
        </div>
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div>
            <h3 style={{
              fontFamily: 'Roboto, system-ui, sans-serif', fontSize: '14px', fontWeight: 700,
              color: t.textPri, margin: 0, lineHeight: 1,
            }}>
              AI Clinical Summary
            </h3>
            <p style={{ fontSize: '10px', color: t.textMuted, margin: '3px 0 0', letterSpacing: '0.06em' }}>
              {summary.source === 'rule_based'
                ? 'Rule-Based Fallback · WHO Protocol'
                : 'Powered by LLM · Auto-Generated'}
            </p>
          </div>
          {/* H-7: Visibly disclose to the clinician whether the summary came
              from the LLM or the deterministic rule-based fallback. Removes
              the silent-switch failure mode where a clinician trusts AI-
              labelled output that is actually rule-based heuristics. */}
          {summary.source && (
            <span
              title={
                summary.source === 'llm'
                  ? 'Generated by Gemini LLM'
                  : `Deterministic rule-based fallback${summary.reason ? ` (${summary.reason})` : ''}`
              }
              style={{
                marginLeft: 'auto',
                fontSize: '9px', fontWeight: 700, letterSpacing: '0.08em',
                padding: '4px 8px', borderRadius: '999px',
                textTransform: 'uppercase',
                background: summary.source === 'llm'
                  ? 'rgba(139,92,246,0.12)'
                  : 'rgba(245,158,11,0.12)',
                color: summary.source === 'llm' ? '#8B5CF6' : '#D97706',
                border: summary.source === 'llm'
                  ? '1px solid rgba(139,92,246,0.25)'
                  : '1px solid rgba(245,158,11,0.3)',
              }}
            >
              {summary.source === 'llm' ? 'AI Generated' : 'Rule-Based Fallback'}
            </span>
          )}
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        <p style={{ fontSize: '12px', color: t.textSec, margin: 0, lineHeight: 1.5 }}>
          <strong style={{ color: t.textPri }}>Progress:</strong> {summary.labor_progress}
        </p>
        
        <p style={{ fontSize: '12px', color: t.textSec, margin: 0, lineHeight: 1.5 }}>
          <strong style={{ color: '#F59E0B' }}>Risk:</strong> {summary.risk_status}
        </p>
        
        <p style={{ fontSize: '12px', color: t.textSec, margin: 0, lineHeight: 1.5 }}>
          <strong style={{ color: '#10B981' }}>Attention:</strong> {summary.suggested_attention}
        </p>
      </div>
    </div>
  );
};

export default AISummaryBox;
